export const UPDATE_USER = "UPDATE_USER";

export const LOGIN = "LOGIN";
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGING_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const GET_SUBJECTS = "GET_SUBJECTS";
export const GET_SUBJECTS_REQUEST = "GET_SUBJECTS_REQUEST";
export const GET_SUBJECTS_SUCCESS = "GET_SUBJECTS_SUCCESS";
export const GET_SUBJECTS_FAILURE = "GET_SUBJECTS_FAILURE";
